failFast: true

complexity:
  TooManyFunctions:
    thresholdInClasses: 20

comments:
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false


test-pattern:
  active: true

  patterns:
  - '.*/test/.*'
  - '.*Test.kt'
  - '.*Spec.kt'
  - '.*/androidTest/.*'

  exclude-rule-sets:
  - 'comments'

  exclude-rules:
  - 'NamingRules'
  - 'WildcardImport'
  - 'MagicNumber'
  - 'MaxLineLength'
  - 'LateinitUsage'
  - 'StringLiteralDuplication'
  - 'SpreadOperator'
  - 'TooManyFunctions'
  - 'UnsafeCast'
  - 'UnderscoresInNumericLiterals'
