failFast: true

complexity:
  TooManyFunctions:
    thresholdInClasses: 15

test-pattern:
  active: true

  patterns:
    - '.*/test/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
    - '.*/androidTest/.*'

  exclude-rule-sets:
    - 'comments'

  exclude-rules:
    - 'NamingRules'
    - 'WildcardImport'
    - 'MagicNumber'
    - 'MaxLineLength'
    - 'LateinitUsage'
    - 'StringLiteralDuplication'
    - 'SpreadOperator'
    - 'TooManyFunctions'
    - 'UnsafeCast'


comments:
  active: true

  CommentOverPrivateFunction:
    active: false
